-- RUN THIS IN YOUR SUPABASE SQL EDITOR --

-- 1. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price DECIMAL NOT NULL,
    unit TEXT DEFAULT 'm²',
    category TEXT,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Ingredients (Bahan Baku) Table
CREATE TABLE IF NOT EXISTS ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    stock DECIMAL DEFAULT 0,
    unit TEXT DEFAULT 'pcs',
    min_stock DECIMAL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT,
    phone TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Contacts (Customers & Suppliers) Table
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    type TEXT CHECK (type IN ('Customer', 'Supplier')),
    company TEXT,
    points INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT,
    email TEXT,
    role TEXT DEFAULT 'kasir',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Inventory Logs (Kartu Stok) Table
CREATE TABLE IF NOT EXISTS inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT REFERENCES ingredients(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('in', 'out')),
    quantity DECIMAL NOT NULL,
    previous_stock DECIMAL NOT NULL,
    current_stock DECIMAL NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Purchases Table
CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_no TEXT NOT NULL,
    ingredient_id BIGINT REFERENCES ingredients(id),
    supplier_id BIGINT REFERENCES contacts(id),
    quantity DECIMAL NOT NULL,
    unit_price DECIMAL NOT NULL,
    total_price DECIMAL NOT NULL,
    payment_status TEXT CHECK (payment_status IN ('lunas', 'hutang')),
    note TEXT,
    purchase_date TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Machines (Mesin Cetak) Table
CREATE TABLE IF NOT EXISTS machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT,
    status TEXT DEFAULT 'aktif' CHECK (status IN ('aktif', 'maintenance', 'rusak')),
    ip_address TEXT,
    last_service TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Orders (Penjualan) Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no TEXT NOT NULL,
    items_summary TEXT,
    total_amount DECIMAL NOT NULL,
    paid_amount DECIMAL DEFAULT 0,
    remaining_amount DECIMAL DEFAULT 0,
    payment_method TEXT,
    status TEXT DEFAULT 'selesai',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial categories
INSERT INTO categories (name, description) VALUES
('Banner', 'Layanan cetak banner outdoor/indoor'),
('Spanduk', 'Layanan cetak spanduk kain/flexi'),
('Sticker', 'Layanan cetak sticker dan cutting'),
('Neon Box', 'Layanan pembuatan neon box akrilik'),
('Baliho', 'Layanan cetak baliho ukuran besar'),
('MMT', 'Layanan cetak MMT / Flexi'),
('Backdrop', 'Layanan cetak backdrop event');

-- 11. Machine Usage Logs
CREATE TABLE IF NOT EXISTS machine_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id BIGINT REFERENCES machines(id) ON DELETE CASCADE,
    order_no TEXT,
    item_name TEXT,
    operator_name TEXT,
    start_time TIMESTAMPTZ DEFAULT NOW(),
    end_time TIMESTAMPTZ,
    status TEXT DEFAULT 'completed', -- 'printing', 'completed', 'failed'
    created_at TIMESTAMPTZ DEFAULT NOW()
);
